version: '3'
services:
  imgfront:
    image: heroeapp:latest
    environment:
      PORT: 4200
    ports:
      - 4200:4200
  imgback:
    image: jsonserve:latest
    environment:
      PORT: 3000
    ports:
      - 3000:3000